---
- name: Ensure dependencies are present.
  apt:
    name:
      - curl
    state: present

- name: Install libcurl3 for Ubuntu 16.04 only
  apt: name=libcurl3 state=present
  when: ansible_distribution_release == "xenial"

- name: Install libcurl4 for Ubuntu 18.04 and 20.04
  apt: name=libcurl4 state=present
  when: ansible_distribution_release == "bionic" or ansible_distribution_release == "focal"

- name: Downloading Aerospike sources
  get_url:
    url: "https://download.aerospike.com/download/server/{{ aerospike_version }}/artifact/ubuntu{{ ansible_distribution_major_version }}"
    dest: "/tmp/aerospike.tar.gz"
  register: aerospike_source

- name: Unpacking Aerospike
  unarchive:
    copy: no
    dest: /tmp/
    src: "{{ aerospike_source.dest }}"
  when: aerospike_source.changed
  register: aerospike_source_unpack

- name: Installing Aerospike
  become: yes
  shell: asinstall
  args:
    chdir: "/tmp/aerospike-server-community-{{ aerospike_version }}-ubuntu{{ ansible_distribution_version }}"
  when: aerospike_source_unpack|changed
