---
- name: Converge
  hosts: all
  become: true

  vars:
    aerospike_version: "5.6.0.5"

  pre_tasks:
    - import_tasks: playbook-setup.yml

  roles:
    - role: gesof.aerospike

  post_tasks:
    - name: Check the installed Ansible version.
      command: aerospiked -V
      register: aerospike_version
      failed_when: "'5.6.0.5' not in aerospike_version.stderr"
      changed_when: false
      tags: ['skip_ansible_lint']

    - name: Verify Aerospike is running on port 3000.
      shell: 'curl -sI localhost:3000 | grep -q "Via: .* aerospike"'
      args:
        warn: false
      changed_when: false
      tags: ['skip_ansible_lint']
